<?php
/**
 * ResponseChatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResponseChatTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseChat
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseChatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseChat"
     */
    public function testResponseChat()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "is_group"
     */
    public function testPropertyIsGroup()
    {
    }

    /**
     * Test attribute "is_read_only"
     */
    public function testPropertyIsReadOnly()
    {
    }

    /**
     * Test attribute "unread_count"
     */
    public function testPropertyUnreadCount()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "pinned"
     */
    public function testPropertyPinned()
    {
    }

    /**
     * Test attribute "is_muted"
     */
    public function testPropertyIsMuted()
    {
    }

    /**
     * Test attribute "mute_expiration"
     */
    public function testPropertyMuteExpiration()
    {
    }

    /**
     * Test attribute "group_metadata"
     */
    public function testPropertyGroupMetadata()
    {
    }
}
